// selenuim/react-calculator/client/components/app.jsx
import React from 'react'; // import react module
import Screen from './screen'; // Import our screen component from this directory
import Button from './button'; // Import our button component from this directory

// create a class which extends react component
class App extends React.Component {
  constructor() {
    super();
    // set our default state
    this.state = {
      question: '',
      answer: ''
    }
    // Bind our handleClick method (sets 'this' explicitly to refer to this componenent)
    // We did this because 'this' would refer to the source of the click events
    this.handleClick = this.handleClick.bind(this);
  }

  // Render function to creat component to be rendered on the DOM.
  // This method must return a single parent element as you can see here.
  // The component is wrapped around () to make it a single expression.
  render() {
    return (
      <div className="frame">
        <div className="calculator-title">
          R_N Calculator
        </div>
        <Screen question={this.state.question} answer={this.state.answer}/>
        <div className="button-row">
          <Button id={'1'} label={'1'} handleClick={this.handleClick} type='input' />
          <Button id={'2'} label={'2'} handleClick={this.handleClick} type='input' />
          <Button id={'3'} label={'3'} handleClick={this.handleClick} type='input' />
          <Button id={'4'} label={'4'} handleClick={this.handleClick} type='input' />
          <Button id={'sub'} label={'-'} handleClick={this.handleClick} type='action' />
          <Button id={'add'} label={'+'} handleClick={this.handleClick} type='action' />
        </div>
        <div className="button-row">
          <Button id={'5'} label={'5'} handleClick={this.handleClick} type='input' />
          <Button id={'6'} label={'6'} handleClick={this.handleClick} type='input' />
          <Button id={'7'} label={'7'} handleClick={this.handleClick} type='input' />
          <Button id={'8'} label={'8'} handleClick={this.handleClick} type='input' />
          <Button id={'multiple'} label={'*'} handleClick={this.handleClick} type='action' />
          <Button id={'divide'} label={'/'} handleClick={this.handleClick} type='action' />
        </div>
        <div className="button-row">
          <Button id={'9'} label={'9'} handleClick={this.handleClick} type='input' />
          <Button id={'dot'} label={'.'} handleClick={this.handleClick} type='input' />
          <Button id={'0'} label={'0'} handleClick={this.handleClick} type='input' />
          <Button id={'cls'} label={'Cls'} handleClick={this.handleClick} type='action' />
          <Button id={'equal'} label={'='} handleClick={this.handleClick} type='action' />
        </div>
      </div>
    );
  }

  // our method to handle all click events from our buttons
  handleClick(event){
    const value = event.target.value; // get the value from the target element (button)
    switch (value) {
      case '=': { // if it's an equal sign, use the eval module to evaluate the question
        // convert the answer (in number) to String
        const answer = this.calculateExpression(this.state.question).toString();
        // update answer in our state.
        this.setState({ answer });
        break;
      }
      case 'Cls': {
        // if it's the Cls sign, just clean our question and answer in the state
        this.setState({ question: '', answer: '' });
        break;
      }
      default: {
        // for every other commmand, update the answer in the state
        this.setState({ question: this.state.question += value})
        break;
      }
    }
  }
  calculateExpression(expressionStr){
    const operatorsRegex = /\+|-|\*|\//;
    // Find the arithmetic operator
    let operator = expressionStr.match(operatorsRegex)[0];
    let argumentsArr = expressionStr.split(operatorsRegex);
    let leftNum = parseInt(argumentsArr[0]);
    let rightNum = parseInt(argumentsArr[1]);
    switch (operator) {
      case '+':{
        return this.add(leftNum, rightNum);
      }
      case '-':{
        return this.sub(leftNum, rightNum);
      }
      case '/':{
        return this.divide(leftNum, rightNum);
      }
      case '*':{
        return this.multiple(leftNum, rightNum);
      }
    }
  }

  add(num1, num2){
    return num1 + num2;
  }

  sub(num1, num2){
    return num1 - num2;
  }

  multiple(num1, num2){
    if(num2 ==1){
      console.log("meaningless")
    }
    return num1 * num2;
  }

  divide(number1, number2 = 1){
    if(number2 == 0){
      return 0;
    }
    else{
      return number1 / number2
    }
  }
}

// export our frame component. To be used in our client/index.js file
export default App;

// selenuim/angular-calculator/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  private question = '';
  private answer = '';


  handleClick(targetId: string) {
    switch (targetId) {
      case '=': { // if it's an equal sign, use the eval module to evaluate the question
        // convert the answer (in number) to String
        this.answer = this.calculateExpression(this.question).toString();
        break;
      }
      case 'cls': {
        // if it's the Cls sign, just clean our question and answer in the state
        this.answer = '';
        this.question = '';
        break;
      }
      default: {
        // for every other commmand, update the answer in the state
        this.question += targetId;
        break;
      }
    }
  }

  calculateExpression(expressionStr: string) {
    const operatorsRegex = /\+|-|\*|\//;
    // Find the arithmetic operator
    const operator = expressionStr.match(operatorsRegex)[0];
    const argumentsArr = expressionStr.split(operatorsRegex);
    const leftNum = parseInt(argumentsArr[0]);
    const rightNum = parseInt(argumentsArr[1]);
    switch (operator) {
      case '+': {
        return this.add(leftNum, rightNum);
      }
      case '-': {
        return this.sub(leftNum, rightNum);
      }
      case '/': {
        return this.divide(leftNum, rightNum);
      }
      case '*': {
        return this.multiple(leftNum, rightNum);
      }
    }
  }

  add(num1, num2) {
    return num1 + num2;
  }

  sub(num1, num2) {
    return num1 - num2;
  }

  multiple(num1, num2) {
    if (num2 === 1) {
      console.log('meaningless');
    }
    return num1 * num2;
  }

  divide(number1, number2 = 1) {
    if (number2 === 0) {
      return 0;
    } else {
      return number1 / number2;
    }
  }
}

<table>
  <tr>
    <td colspan="4"><input type="text" [(ngModel)]="question" id="question" class="input"></td>
    <td colspan="4"><input type="text" [(ngModel)]="answer" id="answer" class="input"></td>
  </tr>
  <tr>
    <td width="45"><button id="7" class="button" (click)="handleClick('7')">7</button></td>
    <td width="45"><button id="8" class="button" (click)="handleClick('8')">8</button></td>
    <td width="45"><button id="9" class="button" (click)="handleClick('9')">9</button></td>
    <td width="45"><button id="add" class="button" (click)="handleClick('+')">+</button></td>
  </tr>
  <tr>
    <td width="45"><button id="4" class="button" (click)="handleClick('4')">4</button></td>
    <td width="45"><button id="5" class="button" (click)="handleClick('5')">5</button></td>
    <td width="45"><button id="6" class="button" (click)="handleClick('6')">6</button></td>
    <td width="45"><button id="sub" class="button" (click)="handleClick('-')">-</button></td>
  </tr>
  <tr>
    <td width="45"><button id="1" class="button" (click)="handleClick('1')">1</button></td>
    <td width="45"><button id="2" class="button" (click)="handleClick('2')">2</button></td>
    <td width="45"><button id="3" class="button" (click)="handleClick('3')">3</button></td>
    <td width="45"><button id="multiple" class="button" (click)="handleClick('*')">*</button></td>
  </tr>
  <tr>
    <td width="45"><button id="0" class="button" (click)="handleClick('0')">0</button></td>
    <td width="45"><button id="cls" class="button" (click)="handleClick('cls')">cls</button></td>
    <td width="45"><button id="divide" class="button" (click)="handleClick('/')">/</button></td>
    <td width="45"><button id="equal" class="button" (click)="handleClick('=')">=</button></td>
  </tr>
</table>
